### DISCUSSION TITLE
How do I set a default language for my site?

### DISCUSSION THREAD

**Discussion by ziyouwa** [welpo/tabi#253] [Q&A] [answered]
I followed [it](https://welpo.github.io/tabi/blog/faq-languages/#how-do-i-set-a-default-language-for-my-site) to set as below:

```toml
base_url = "https://xxx.xx.xx"
title = "XXX"
description = "xxx"
author = "xxx"
generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

default_language = "zh"

taxonomies = [{name = "tags", feed = true}]

[search]
...
[link_checker]
internal_level = "warn"

[languages.zh-Hans]
title = "中文"
description = "中文"
author = "中文"
build_search_index = false
taxonomies = [{name = "tags", feed = true}]

[extra]
...
```
but default display english. If change [languages.zh-Hans] to [languages.zh] , it show error than xxxx is specified twice. How to correctly set the default language to Chinese?

**Comment by ziyouwa** [comment]
I try to also set default_language = "zh-Hans", it show the error xxx twice specified.

**Comment by welpo** [comment, marked as answer]
```toml
base_url = "https://xxx.xx.xx"
title = "中文"
description = "中文"
author = "中文"
generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

default_language = "zh-Hans"

taxonomies = [{name = "tags", feed = true}]

[search]
...
[link_checker]
internal_level = "warn"

[extra]
...
```

**Comment by ziyouwa** [comment]
My ideal solution  is using default configuration for English, and then use i18n/zh-Hans.toml and _index.zh-Hans.md and etc. for Chinese adaptation. Additionally, there could be a configuration option, like current_language, to achieve a redirect-like effect. For instance, if current_language is set to zh-Hans, accessing https://blog.site/ would automatically redirect to https://blog.site/zh-Hans. This approach allows a single codebase to accommodate various languages as the default, with the flexibility to modify this parameter as needed. I am trying to manually set the redirection temporarily to solve the problem now.

**Reply by welpo** [reply]
I don't understand your goal, sorry.

> My ideal solution is using default configuration for English, and then use i18n/zh-Hans.toml and _index.zh-Hans.md

Have you tried this:

```toml
base_url = "https://xxx.xx.xx"
title = "title"
description = "description"
author = "ziyouwa"
generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

default_language = "en"

taxonomies = [{name = "tags", feed = true}]


[languages.zh-Hans]
title = "中文"
description = "中文"
build_search_index = true
taxonomies = [{name = "tags", feed = true}]
```

When users visit your URL, they'll see the English text (articles named `index.md`). If they click on the world globe and choose Chinese, they'll see the Chinese Simplified text (articles named `index.zh-Hans.md`).
