### DISCUSSION TITLE
Support Plural Forms

### DISCUSSION THREAD

**Discussion by TheAwiteb** [welpo/tabi#273] [General]
Hello @welpo, I want to support plural forms in Tabi, but this needs to be done in the `i18n` directory. So do you mind?

My language is Arabic, and it has a few plural forms (unlike English, which only has two). I can help you with the translations if you want.

> [!NOTE]
> I don't know if aouther languages have more than two plural forms, I'll add to Arabic only and keep the rest as they are.

For example, the word "minute" in Arabic has three plural forms:

- دقيقة (singular)
- دقيقتان (dual)
- دقائق (few)
- دقيقة (many)

So, I will add the following to the translations file:

```toml
one_read_minute = "دقيقة" # Only one minute
two_read_minute = "دقيقتان" # Two minutes
few_read_minute = "دقائق" # Numbers from 3 to 10
many_read_minute = "دقيقة" # Numbers higher than 10
```

And the same thing for posts and tags, I think that's only.
