### DISCUSSION TITLE
What is the best way to replace the existing font with a new font?

### DISCUSSION THREAD

**Discussion by soumendrak** [welpo/tabi#376] [Q&A] [answered]
I want to use [Atkinson hyperlegible](https://brailleinstitute.org/freefont) for my regular text on my website. I did not find a doc on how to install a custom font. Please help.

**Comment by welpo** [comment]
Good choice!

To customise the font, you'll need (1) add the font to your `static` directory and (2) load a CSS file to override the tabi defaults. For example:

```css
@font-face {
    src: local('Atkinson Hyperlegible'),
        url('/fonts/Atkinson-Hyperlegible-Regular-102a.woff2') format("woff2");
    font-family: 'Atkinson Hyperlegible';
    font-display: swap;
}

:root {
    --serif-font: 'Atkinson Hyperlegible', serif;
}
```

You can load this file in two ways: with [`stylesheets`](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#custom-css) or with [`skins`](https://welpo.github.io/tabi/blog/customise-tabi/#skins). They are functionally identical, provided you set `stylesheets` in `config.toml`.

The CSS assumes the font file is at `static/fonts/`.

Hope that helps!

**Reply by soumendrak** [reply]
My folder structure is this:

```
.
├── README.md
├── config.toml
├── content
│   ├── _index.md
│   ├── _index.or.md
├── static
│   ├── css
│   │   └── custom.css
│   ├── fonts
│   │   └── Atkinson-Hyperlegible-Regular-102a.woff2
│   └── images
│       ├── default_cover.webp
```
In `config.toml`

```toml
[extra]
stylesheets = ["css/custom.css"]
```
The same script is inside the CSS file as suggested. Still not working.
![image](https://github.com/user-attachments/assets/c28a0e1d-708b-41d7-97c6-0bcb319e90a4)

**Reply by welpo** [reply]
I tested the setup I suggested earlier and it loaded the font fine.

Does the browser try to load the file? I'd check for loading errors (e.g. a 404 when getting the font). Does the custom css have the expected content? If you try to manually navigate to 127.0.0.1:111/fonts/Atkinsons…, does it load the font, or does it 404? Is the name on the CSS the exact name of the woff2 file?

If you're using a subdirectory, you may need to change the `local` path on the font to remove the first slash (so `url('fonts/…`).

**Reply by soumendrak** [reply]
I see the font is working when I go inside a content page [like this](https://www.soumendrak.com/blog/attrs/). 
However, the [homepage](https://www.soumendrak.com/) and section pages, need to be fixed. Also, I do not see any error.
- [Website source code](https://github.com/soumendrak/website-v2)

**Reply by welpo** [reply]
Interesting! I'll do a deep dive later and report back.

P.S: Thank you so much for my first GitHub sponsorship! It means a lot~

**Reply by welpo** [reply, marked as answer]
Ah, right!

tabi uses three fonts: one for headers / main page (sans serif), one for article/page content (serif), and one for code.

The [defaults](https://github.com/welpo/tabi/blob/e73a50c3c953cf2fcf5fcce49cf893164c51e278/sass/main.scss#L97-L99) are:

```
--sans-serif-font: 'Inter', Helvetica, Arial, sans-serif;
--serif-font: 'Source Serif', 'Georgia', serif;
--code-font: 'Cascadia Code';
```

You'll need to override each variable separately. If you want to use the same font everywhere (except code) I see two options:
- Override the CSS variable `sans-serif-font` to match `serif-font`;
- Only override `serif-font` and set `override_serif_with_sans = true` in your configuration ([docs](https://welpo.github.io/tabi/blog/mastering-tabi-settings/#sans-serif-font))

Either option should achieve your goal!

**Reply by soumendrak** [reply]
Thanks, I went with the first option. 

For future readers, 
this is my final CSS file:

```css
@font-face {
    src: local('Atkinson Hyperlegible'),
        url('/fonts/Atkinson-Hyperlegible-Regular-102a.woff2') format("woff2");
    font-family: 'Atkinson Hyperlegible';
    font-display: swap;
}

:root {
    --serif-font: 'Atkinson Hyperlegible', serif;
    --sans-serif-font: 'Atkinson Hyperlegible', serif;
}
```
