### DISCUSSION TITLE
Skins not affecting dark theme?

### DISCUSSION THREAD

**Discussion by JVimes** [welpo/tabi#378] [Q&A] [answered]
The skins don't seem to be affecting dark theme, for me. Is that expected, or am I using it wrong?
Thanks!

**Comment by welpo** [comment]
Hello!

Last I checked, skins do affect both themes, as long as they are properly defined. Are you using a built-in skin, or a custom one? If the latter, can you share it?

If it's a custom one, my guess is it's not following [this format](https://welpo.github.io/tabi/blog/customise-tabi/#create-your-own-skin) for the dark theme variables:

```css
:root {
    --primary-color: #087e96;
}

[data-theme='dark'] {
    --primary-color: #91e0ee;
}
```
