### ISSUE TITLE
How do I set a default language for my site?

### ISSUE THREAD

**Issue by ziyouwa** [welpo/tabi#252]
I followed [it](https://welpo.github.io/tabi/blog/faq-languages/#how-do-i-set-a-default-language-for-my-site) to set as below:

```toml
base_url = "https://xxx.xx.xx"
title = "XXX"
description = "xxx"
author = "xxx"
generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

default_language = "zh"

taxonomies = [{name = "tags", feed = true}]

[search]
...
[link_checker]
internal_level = "warn"

[languages.zh-Hans]
title = "中文"
description = "中文"
author = "中文"
build_search_index = false
taxonomies = [{name = "tags", feed = true}]

[extra]
...
```
but default display english. If change [languages.zh-Hans] to [languages.zh] , it show error than xxxx is specified twice. How to correctly set the default language to Chinese?

**Comment by ziyouwa** [comment]
I try to also set default_language = "zh-Hans", it show the error xxx twice specified.

**Comment by welpo** [comment]
```toml
base_url = "https://xxx.xx.xx"
title = "中文"
description = "中文"
author = "中文"
generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

theme = "tabi"

default_language = "zh-Hans"

taxonomies = [{name = "tags", feed = true}]

[search]
...
[link_checker]
internal_level = "warn"

[extra]
...
```
