### ISSUE TITLE
Broken spacing in LTR next/prev post navigation

### ISSUE THREAD

**Issue by welpo** [welpo/tabi#274]
# Bug Report

## Environment

Zola version: `0.18.0`
tabi version or commit: b3ef23f305736ce5c784026e163796c11497b6f9

## Expected Behavior

RTL languages should have proper spacing, just like LTR:

![ss](https://github.com/welpo/tabi/assets/6399341/c8c218b4-dbb3-4862-92b1-926aea2f52b7)

## Current Behavior

![ss](https://github.com/welpo/tabi/assets/6399341/a0461663-8a95-4deb-9038-311cd0dbcb35)

## Step to Reproduce

In config.toml:

```toml
default_language = "ar"

[extra]
show_previous_next_article_links = true
```
