### ISSUE TITLE
Change Language icon not showing

### ISSUE THREAD

**Issue by Myrdincx** [welpo/tabi#296]
# Bug Report

## Environment
Zola version: 0.18.0
tabi version or commit: latest

## Expected Behavior
There should have been a language changing icon

## Current Behavior
There is no language changing icon

## Step to Reproduce
Changed the `config.toml` to include Dutch as well.
Made the `_index.nl.md` files and created a blog post with `index.nl.md`
Served the website, now the blog post shows up twice, once in Dutch, once in English.
However, there is no button to change the language of the website, it defaults back to English

I'm probably doing something wrong somewhere, but I have no clue what it could be.

**Comment by welpo** [comment]
> Changed the `config.toml` to include Dutch as well.

Can you elaborate on this? Did you follow the steps from [the docs](https://welpo.github.io/tabi/blog/faq-languages/#how-do-i-enable-multilingual-support)?

**Comment by Myrdincx** [comment]
Yeah, as far as I can see, I followed all the steps from the docs.
I'm not quite sure why it isnt working.
The language part of my `config.toml` file:

```toml
base_url = "example.com"
theme = "tabi"

default_language = "en"

title = "TITLE"
description = "DESCRIPTION"
author = "Myrdin"

generate_feed = true
compile_sass = true
minify_html = false
build_search_index = true
taxonomies = [{name = "tags", feed = true}]

[language.nl]
title = "TITEL"
description = "BESCHRIJVING"
author = "Myrdin"

generate_feed = true
compile_sass = true
minify_html = false
build_search_index = true
taxonomies = [{name = "tags", feed = true}]
```
